In [7]:
import numpy as np
array1=np.array(range(6))
array1.shape

(6,)

In [9]:
array1.shape=2,3
print(array1)

[[0 1 2]
 [3 4 5]]


In [11]:
array2=array1.reshape(3,2)
print(array2)

[[0 1]
 [2 3]
 [4 5]]


In [12]:
array1[1,2]=99
print(array1,array2)

[[ 0  1  2]
 [ 3  4 99]] [[ 0  1]
 [ 2  3]
 [ 4 99]]


In [14]:
array3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array3)        

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
array4=np.arange(13,1,-1)
array4

array([13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2])

In [18]:
array4.shape=2,2,3
array4

array([[[13, 12, 11],
        [10,  9,  8]],

       [[ 7,  6,  5],
        [ 4,  3,  2]]])

In [20]:
array6=np.linspace(1,12,12)
array6

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.])

In [21]:
array7=np.linspace(1,12,12,dtype=int)
array7

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [24]:
a=np.zeros((4,5))
b=np.ones((2,5,4),dtype=np.int16)
c=np.empty((3,2))
a,b,c

(array([[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]]), array([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],
 
        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]], dtype=int16), array([[  0.00000000e+000,   4.94065646e-324],
        [  9.88131292e-324,   1.48219694e-323],
        [  1.97626258e-323,   2.47032823e-323]]))

In [29]:
a1=np.linspace(1,26,6,dtype=int)
a1,a1[3],a1[1:3],a1[:5],a1[2:],a1[2:-1]

(array([ 1,  6, 11, 16, 21, 26]),
 16,
 array([ 6, 11]),
 array([ 1,  6, 11, 16, 21]),
 array([11, 16, 21, 26]),
 array([11, 16, 21]))

In [31]:
a2=a1[0:3:1]
a1[0]=19
a2[0]

19

In [33]:
a3=a1[[0,1,4]]
a1[0]=23
a3[0]

19

In [35]:
na1=np.array(np.arange(24),dtype=int).reshape(4,6)
na1[:2,1:],na1[[2,3],[2,4]]

(array([[ 1,  2,  3,  4,  5],
        [ 7,  8,  9, 10, 11]]), array([14, 22]))

In [39]:
na2=na1.reshape(2,3,4)
na2,na2[(1,1,2)],na2[1,1,2],na2[[1,1,0],[0,1,2],[2,3,1]]

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]), 18, 18, array([14, 19,  9]))

In [47]:
ar1=np.array(np.arange(5))
np.add(ar1,4)
ar1,np.add(ar1,4),np.add(ar1,np.add(ar1,4))

(array([0, 1, 2, 3, 4]), array([4, 5, 6, 7, 8]), array([ 4,  6,  8, 10, 12]))

In [52]:
a=np.array([10,20,30,40,50])
a**2,10*np.cos(a),a<40

(array([ 100,  400,  900, 1600, 2500]),
 array([-8.39071529,  4.08082062,  1.5425145 , -6.66938062,  9.64966028]),
 array([ True,  True,  True, False, False], dtype=bool))